### PR TITLE
Normalize drop-shadow styling and rounded border for text inputs in m…

### PR DESCRIPTION
**Pull request by fulcircle**
…obile Safari

Feel free to close or modify if this is not the right place or doesn't look correct.

### CODE REVIEW

**Comment by jacobgunnarsson** [comment]
I agree, but lets put this in /base/_base.scss instead? To not modify the Normalize vendor code in case we want to update Normalize, these styles will probably be forgot and lost. 

Come to think of it _normalize.scss should really be put in /vendor instead of /base.

**Comment by jacobgunnarsson** [comment]
I moved your addition @fulcircle from _normalize.scss to _base.scss and also applied it more generally to input, textarea and button because I know iOS Safari likes to mess with those as well.

**Comment by fulcircle** [comment]
@jacobgunnarsson From what I read, if we apply the -webkit-appearance: none generally to input elements, Chrome will not render radio buttons or checkboxes correctly, which is why I applied it specifically to text inputs (though we could probably add email, password, etc).  I'll update the PR later today when I have some time to test and modify.

**Comment by jacobgunnarsson** [comment]
Moved the -webkit-appearance property to only apply to text inputs, password inputs or textareas.

**Pull request merged**
